// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ammrkpzxmhiawuqheiuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbXJrcHp4bWhpYXd1cWhlaXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTg0NTAsImV4cCI6MjA2OTg3NDQ1MH0.t8IAVFzhXgJ16hVB3eE4u52Ng8P-ULRGRijiyPrj8CE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});